# Матрицы

Прямоугольная таблица чисел.

Обозначение $x_{m,n}$, где m - число строк, n - число столбцов.
$x_{2,3}$:
\begin{pmatrix}
1 & 2 & 3\\
a & b & c
\end{pmatrix}

### Предназначение:

1) Набор векторов



2) Преобразование векторов и систем координат (линейное отображение)


3) Соотношение между векторами "биленейная форма"

### Python

In [4]:
import numpy as np
# a_{2,3}
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Нулевая матрица
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [11]:
# 1 на диоганали
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Матричные операции

## Сложение и вычитание

In [ ]:
A + B =

\begin{pmatrix}
a_{1, 1} + b_{1, 1} & ... a_{m, n} + b_{m,n}\\
a_{m, 1} + b_{m, 1} & ... a_{m, n} + b_{m, n}
\end{pmatrix}

##### Требование: Одинаковая размерность

##### Принцип: каждый элемент складывается с каждым

### Умножение матриц

2 матрицы размерностью $m * n$ и $n * k$ можно перемножить по правилу "строка на столбец":


$ A \cdot B =$ 

\begin{pmatrix}
(a_m, b_k)
\end{pmatrix}

Где $(a_i, b_j)$ - *скалярное произведенеи векторов*

<img src="https://i.ytimg.com/vi/llwuoLzPbdE/hqdefault.jpg" />

<img src="https://yotx.ru/Images/matrix-multiply-by-matrix-3.gif" />

#### Свойства умножения матриц

$A \cdot (B + C) = A \cdot B + A \cdot C$

Как правило: $A \cdot B <> B \cdot A$

(да же с подходящими размерностями)

### Python

In [30]:
a = np.array([[1, 2], [4,5]])
b = np.array([[-2,3], [0, 1]])
# Умножение матриц
a @ b

array([[-2,  5],
       [-8, 17]])

In [34]:
c = np.dot(a, b)
# То же умножение матриц
c

array([[-2,  5],
       [-8, 17]])

#### Перемножение матрциы и вектора: аналогично перемножение матрицы на матрицу с 1й строкой или 1м столбцом